name: Build & Push MySQL Docker Image

on:
  push:
    branches:
      - main  # Chạy khi có push lên nhánh main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERUSERNAME }}
          password: ${{ secrets.SECRETTOKEN }}

      - name: Build Docker Image
        run: |
          docker build -t tien22012003/mysql:latest .

      - name: Push Docker Image to Docker Hub
        run: |
          docker push tien22012003/mysql:latest
