name: Test Action

on:
  push:
    branches:
      - main  # Chạy khi có push lên nhánh main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Print a message
        run: echo "✅ GitHub Action is running successfully!"
